server:
  port: 9003

spring:
  application:
    name: sender
  kafka:
    bootstrap-servers: localhost:9092
    topics:
      notifications:
        email: email-notification
        phone: phone-notification
        telegram: telegram-notification


notification:
  maxRetryAttempts: 3
  services:
    telegram:
      token: 8368549899:AAEqnDAEVKOJRnf7jOiIChPN4iW5doZcZ0Q


services:
  notification: notification-service